#!/bin/bash

set -e

SSH_KEY=""
NODE_A=`terraform output node_a`
NODE_B=`terraform output node_b`

# Update IP addresses in scripts.
sed -i '' -e "s/NodeA = .*,/NodeA = \"${NODE_A}\",/" app_config.txt
sed -i '' -e "s/NodeB = .*,/NodeB = \"${NODE_B}\",/" app_config.txt

sed -i '' -e "s/NODE_A=.*/NODE_A=\"${NODE_A}\"/" trigger
sed -i '' -e "s/NODE_B=.*/NODE_B=\"${NODE_B}\"/" trigger

# Sync over code and config.

rsync -av --delete -e "ssh -i ${SSH_KEY}" ../_rel ubuntu@${NODE_A}:/opt/setconcile
scp -i ${SSH_KEY} app_config.txt ubuntu@${NODE_A}:/opt/setconcile/etc/config.txt
#ssh -i ${SSH_KEY} ubuntu@${NODE_A} rm -rf /opt/setconcile/_rel
#tar -C .. -cz _rel | ssh -i ${SSH_KEY} ubuntu@${NODE_A} 'tar -xzf - -C /opt/setconcile'

rsync -av --delete -e "ssh -i ${SSH_KEY}" ../_rel ubuntu@${NODE_B}:/opt/setconcile
scp -i ${SSH_KEY} app_config.txt ubuntu@${NODE_B}:/opt/setconcile/etc/config.txt

