#!/bin/bash

set -e

SSH_KEY=""
NODE_A="52.18.251.31"
NODE_B="54.148.130.99"

# Fresh build.
make -C ..

# Update IP addresses in scripts.
sed -i -e "s/NodeA = .*,/NodeA = \"${NODE_A}\",/" config.txt
sed -i -e "s/NodeB = .*,/NodeB = \"${NODE_B}\",/" config.txt

sed -i -e "s/NODE_A=.*/NODE_A=\"${NODE_A}\"/" trigger
sed -i -e "s/NODE_B=.*/NODE_B=\"${NODE_B}\"/" trigger

# Sync over code and config.
rsync -avs --delete -e "ssh -i ${SSH_KEY}" ../_rel ubuntu@${NODE_A}:/opt/setconcile
scp -i ${SSH_KEY} config.txt ubuntu@${NODE_A}:/opt/setconcile/etc/config.txt

rsync -avs --delete -e "ssh -i ${SSH_KEY}" ../_rel ubuntu@${NODE_B}:/opt/setconcile
scp -i ${SSH_KEY} config.txt ubuntu@${NODE_B}:/opt/setconcile/etc/config.txt

