#!/bin/bash

set -e

NODE_A="52.18.251.31"
NODE_B="54.148.130.99"

# Make sure both nodes are up.
curl -f http://${NODE_A}:9001/api/ping
curl -f http://${NODE_B}:9001/api/ping

#time curl -X POST http://${NODE_A}:9001/api/datasets/symm/recons
#time curl -X POST http://${NODE_A}:9001/api/datasets/riak_mini/recons
time curl -X POST http://${NODE_A}:9001/api/datasets/riak_set_a/recons
