#!/bin/bash

set -e

NODE_A=`terraform output node_a`
NODE_B=`terraform output node_b`

# Make sure both nodes are up.
curl -f http://${NODE_A}:9001/api/ping
curl -f http://${NODE_B}:9001/api/ping

#time curl -X POST http://${NODE_A}:9001/api/datasets/mini/recons
#time curl -X POST http://${NODE_A}:9001/api/datasets/symm/recons
#time curl -X POST http://${NODE_A}:9001/api/datasets/riak_mini/recons
time curl -X POST http://${NODE_A}:9001/api/datasets/riak_set_a/recons
